name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 180
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
        compiler: [gcc, clang]
        dependencies: [system, spack]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install dependencies
        if: matrix.dependencies == 'system'
        # We need to remove glib-network, otherwise libproxy might cause crashes.
        run: |
          sudo apt --yes purge glib-networking
          sudo apt --yes --purge autoremove
          sudo aa-remove-unknown
          sudo apt update || true
          sudo apt --yes --no-install-recommends install libglib2.0-dev libbson-dev libleveldb-dev liblmdb-dev libmongoc-dev libsqlite3-dev librados-dev libfuse-dev libmariadb-dev librocksdb-dev
          if test "${{ matrix.os }}" = 'ubuntu-18.04'
          then
            sudo apt --yes --no-install-recommends install python3 python3-pip python3-setuptools python3-wheel ninja-build
            sudo pip3 install meson
          else
            sudo apt --yes --no-install-recommends install meson ninja-build
          fi
      - name: Cache dependencies
        id: cache
        if: matrix.dependencies == 'spack'
        uses: actions/cache@v2
        with:
          path: dependencies
          key: ${{ matrix.os }}-${{ matrix.compiler }}-${{ hashFiles('scripts/spack', 'scripts/install-dependencies.sh') }}
      - name: Install dependencies
        if: matrix.dependencies == 'spack' && steps.cache.outputs.cache-hit != 'true'
        run: |
          ./scripts/install-dependencies.sh full
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: cpp
      - name: Configure
        env:
          CC: ${{ matrix.compiler }}
        run: |
          . scripts/environment.sh
          meson setup --prefix="${GITHUB_WORKSPACE}/julea-install" --buildtype=release --werror bld
      - name: Build
        run: |
          . scripts/environment.sh
          ninja -C bld
      - name: Install
        run: |
          . scripts/environment.sh
          ninja -C bld install
      - name: Analyze with CodeQL
        uses: github/codeql-action/analyze@v1
