name: Documentation

on:
  push:
    branches: [ feature/documentation ] # TODO: Change it to a branch contains releases.

jobs:
  build-push-documentation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # Build the HTML documentation
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
          doxyfile-path: ./doxygen.config
          working-directory: .
    
    # Deploy the HTML documentation to GitHub Pages
    - name: Deploy Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/html/
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true
        publish_branch: docs
